### ISSUE TITLE
[BUG/FEATURE]: Download Form B not working

### ISSUE THREAD

**Issue by Randy-JRA** [skye8-tech/sms-testing-report#1]
### Contact Details

jamrandyankiambom@gmail.com

### What happened?

Expected the form B to download in pdf format nothing happened

### Version

1.0.0 (Default)

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
No log output
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Steps to Reproduce

1. From Student Dashboard go to Courses
2. From Courses at the bottom of page click on view Form B
3. After clicking View From B go bellow page and click on Download 
4. Nothing Happes

### Expected Result

Expected after clicking download, form b should download in pdf format

### Actual Result

Nothing happened, no pup up, no progress bar 

### Operating System

Windows

### Additional Information

No

**Comment by spykelionel** [comment]
Thanks
**RESOLVED**
