### ISSUE TITLE
[BUG/FEATURE]: Cant Find Courses to Register

### ISSUE THREAD

**Issue by Randy-JRA** [skye8-tech/sms-testing-report#2]
### Contact Details

jamrandyankiambom@gmail.com

### What happened?

Opened courses to register and could not find courses to resgister

### Version

1.0.0 (Default)

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
No courses available
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Steps to Reproduce

1. From Student dashboard go to courses
2. From courses displays no courses available to register but yest above I see 09 Courses Resgistered

### Expected Result

1. Expected to See courses to register
2. Expected to see 00 courses registered above not 09 courses registerd

### Actual Result

No courses were available for me to register

### Operating System

Windows 10

### Additional Information

No

**Comment by spykelionel** [comment]
**RESOLVED**
1. To register a course, select academic year, level, and semester
