### ISSUE TITLE
[BUG/FEATURE]: Form B doesnt display my name

### ISSUE THREAD

**Issue by Randy-JRA** [skye8-tech/sms-testing-report#3]
### Contact Details

jamrandyankiambom@gmail.com

### What happened?

after seeing 09 courses registered, i click on view form b and then the available form B doesn't have my name nor my department 

### Version

1.0.0 (Default)

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
nothing happens
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Steps to Reproduce

1. From student dashboard, go to courses,
2. From courses go below the page to view form B
3. Click on View form B
4. Check information on form B (The info is not the students info nor the student department)

### Expected Result

1. To see my info and with the courses i registered

### Actual Result

Seeing info which seems to be like default info

### Operating System

Windows 10

### Additional Information

Nothing

**Comment by spykelionel** [comment]
**RESOLVED**
