### ISSUE TITLE
[BUG/FEATURE]: view fee details showing static content 

### ISSUE THREAD

**Issue by andrew21-mch** [skye8-tech/sms-testing-report#6]
### Contact Details

dev.n.andrew@gmail.com

### What happened?

Can not view fee details 
Shows hard coded values 

### Version

1.0.0 (Default)

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Steps to Reproduce

Go to fee payments 
Select academic year
Click view transactions 
On table that appears, click the eye icon to view

### Expected Result

Load transaction from backend and show 

### Actual Result

Static content showing Instead 

### Operating System

Kali 

### Additional Information

...

**Comment by spykelionel** [comment]
Fixed
