### ISSUE TITLE
View all button on user dashboard not working 

### ISSUE THREAD

**Issue by AfuhEngowei** [skye8-tech/sms-testing-report#7]
### Contact Details

afuhashley@gmail.com

### What happened?

When I click the view all button my browser copies detect rather n returns de definition 

### Version

1.0.0 (Default)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Steps to Reproduce

After login ok the user dashboard click the view all button to view all registered courses

### Expected Result

I expect to see all the courses registered 
In this case none 

### Actual Result

When I click the button i got no response and my browser rather copied the text and returned the definition 

### Operating System

Android

**Comment by spykelionel** [comment]
THANKS
**RESOLVED**
