### ISSUE TITLE
[BUG/FEATURE]: make selects on all pages mobile friendly

### ISSUE THREAD

**Issue by andrew21-mch** [skye8-tech/sms-testing-report#8]
### What happened?

Not a bug

### Version

1.0.0 (Default)

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
No log
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Steps to Reproduce

On all parts of the application where there's a drop down and a button 

### Expected Result

Selects and button are suppose to be on different columns 

___select___
<a href="#"><button > button <button /></a>

### Actual Result

__select__ <a href="#"><button > button <button /></a>

### Operating System

Kali

**Comment by spykelionel** [comment]
**RESOLVED**
